# Generated by Django 4.0.2 on 2022-02-21 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_flight_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='airline_flight',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='airline_name',
        ),
        migrations.AddField(
            model_name='airline',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='airline_name', to='flights.flight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airline',
            name='airline_code',
            field=models.CharField(max_length=2),
        ),
    ]
