# Generated by Django 4.0.2 on 2022-02-21 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_airline_airline_flight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='name',
        ),
        migrations.AddField(
            model_name='airline',
            name='airline_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airline',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='flights.flight'),
            preserve_default=False,
        ),
    ]
