# Generated by Django 4.0.2 on 2022-02-21 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_remove_airline_name_airline_airline_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='flight',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='flights.airline'),
            preserve_default=False,
        ),
    ]
